Support for Yarn 2.0
CircleCI-Public/node-orb pull request #81
Opened 2021-05-08 06:16 UTC by rarous

This adds new `pkg-manager` enum value "yarn-berry" and related changes to CI commands and cache paths.

Closes #69

2021-05-18 13:19 UTC, gmemstr commented
@rarous Does this actually leverage yarn 2 as talked about in #69? It seems like it's still using the original yarn 1.0 command, unless I'm mistaken.

2021-05-18 13:26 UTC, rarous commented
This changes CI command and cache paths.  Yarn 2.x has repo local executable that piggiebacks on yarn CLI. This should work if the repo is yarn 2.x (aka berry).

2021-05-19 09:19 UTC, gmemstr requested changes
We'll want to update the enum in `jobs/test.yml`, otherwise this looks good to me.

2021-05-19 11:19 UTC, gmemstr approved these changes

2021-05-19 11:19 UTC, merged

2021-05-19 11:19 UTC, gmemstr commented
@rarous Thank you for the contribution! This will be live shortly :)

2021-05-19 12:28 UTC, rarous commented
Thank you, I'm already using it in production :)